### ISSUE TITLE
uninitialized tchannel instance is not fork-safe

### ISSUE THREAD

**Issue by blampe** [uber/tchannel-python#115]
An uninitialized `TChannel` instance throws a future onto the ioloop, which then breaks forking.

```python
$ cat test.py
import os

from tchannel import TChannel

t = TChannel('app')

print 'forking'

if os.fork() == 0:
    t.listen()
```

After adding a print statement to `tornado.platform.kqueue:register`:

```
$ python test.py
registered a file descriptor
forking
registered a file descriptor
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    t.listen()
  File "/Users/blampe/src/tchannel-python/tchannel/tchannel.py", line 150, in listen
    return self._dep_tchannel.listen(port)
  File "/Users/blampe/src/tchannel-python/tchannel/tornado/tchannel.py", line 256, in listen
    server.add_sockets(sockets)
  File "/Users/blampe/src/tchannel-python/env/lib/python2.7/site-packages/tornado/tcpserver.py", line 144, in add_sockets
    io_loop=self.io_loop)
  File "/Users/blampe/src/tchannel-python/env/lib/python2.7/site-packages/tornado/netutil.py", line 266, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "/Users/blampe/src/tchannel-python/env/lib/python2.7/site-packages/tornado/ioloop.py", line 704, in add_handler
    self._impl.register(fd, events | self.ERROR)
  File "/Users/blampe/src/tchannel-python/env/lib/python2.7/site-packages/tornado/platform/kqueue.py", line 42, in register
    self._control(fd, events, select.KQ_EV_ADD)
  File "/Users/blampe/src/tchannel-python/env/lib/python2.7/site-packages/tornado/platform/kqueue.py", line 64, in _control
    self._kqueue.control([kevent], 0)
OSError: [Errno 9] Bad file descriptor
```

The future is coming from `self.peers = PeerGroup(self)`, which initializes a `Peer` and creates a future in `self._reset_condition = Condition()`.

**Comment by abhinav** [comment]
`os.fork` creates a separate process. You can't share TChannel instances across processes.

**Comment by blampe** [comment]
@abhinav I think you misunderstand, the problem is that we've scheduled work on the ioloop before forking.

**Comment by junchaowu** [comment]
so the problem is the the fd used by Condition(), is belong to one process?

**Comment by blampe** [comment]
The problem is that both processes actually share the same underlying file descriptor.
