### ISSUE TITLE
Cannot use top-level thrift response in handler

### ISSUE THREAD

**Issue by breerly** [uber/tchannel-python#177]
Unable to define a thrift response at the top level, later using it in a handler:

```python
larry = thrift.load('larry', 'thrift/stooges.thrift')

nyuck = larry.Nyuck(
    name='larry',
    language='python',
)

tchannel = TChannel('larry')

@tchannel.thrift.register(larry.Stooges)
def nyuck(request):
    print '%s nyucks larry' % (request.body)

    # does not work!
    return nyuck

    # works!
    return larry.Nyuck(
        name='larry',
        language='python',
    )
```

Stacktrace:

```
Stooges_nyuck_request({'nyuck': None}) nyucks larry
ERROR:tchannel:An unexpected error has occurred from the handler
Traceback (most recent call last):
  File "/Users/graysonkoonce/Uber/larry/env/lib/python2.7/site-packages/tchannel/tornado/dispatch.py", line 212, in handle_call
    response.write_body(new_resp.body)
  File "/Users/graysonkoonce/Uber/larry/env/lib/python2.7/site-packages/tchannel/tornado/response.py", line 209, in write_body
    body = self.serializer.serialize_body(chunk)
  File "/Users/graysonkoonce/Uber/larry/env/lib/python2.7/site-packages/tchannel/serializer/thrift.py", line 102, in serialize_body
    return self.module.dumps(obj)
  File "/Users/graysonkoonce/Uber/larry/env/lib/python2.7/site-packages/thriftrw/protocol/core.py", line 69, in dumps
    value = obj.__class__.type_spec.to_wire(obj)
  File "/Users/graysonkoonce/Uber/larry/env/lib/python2.7/site-packages/thriftrw/spec/union.py", line 145, in to_wire
    fields.append(field.to_wire(value))
  File "/Users/graysonkoonce/Uber/larry/env/lib/python2.7/site-packages/thriftrw/spec/struct.py", line 266, in to_wire
    value=self.spec.to_wire(value),
  File "/Users/graysonkoonce/Uber/larry/env/lib/python2.7/site-packages/thriftrw/spec/struct.py", line 139, in to_wire
    check.instanceof_surface(self, struct)
  File "/Users/graysonkoonce/Uber/larry/env/lib/python2.7/site-packages/thriftrw/spec/check.py", line 55, in instanceof_surface
    instanceof_class(type_spec, type_spec.surface, value)
  File "/Users/graysonkoonce/Uber/larry/env/lib/python2.7/site-packages/thriftrw/spec/check.py", line 61, in instanceof_class
    'Cannot serialize %r into a "%s".' % (value, type_spec.name)
TypeError: Cannot serialize <function handle at 0x10c441140> into a "Nyuck".
``
 
cc @blampe @abg

**Comment by abhinav** [comment]
The `return nyuck` refers to the function defined as `def nyuck`, not the top-level `nyuck`. :)
